# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='topic',
            new_name='topicc',
        ),
    ]
