# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_auto_20161130_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='topicc',
            new_name='topic',
        ),
    ]
